name: NPM-Publish

on:
  release:
    types: [created]

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 10
      - uses: CultureHQ/actions-yarn@master
        with:
          args: install
      - run: npm config set commit-hooks false
      - run: npm config set git-tag-version false
  
  build:
    needs: install
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 10
      - uses: CultureHQ/actions-yarn@master
        with:
          args: build
      - run: npm version patch

  publish:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 10
          registry-url: https://registry.npmjs.org/
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_Token}}

  commit:
    needs: publish
    runs-on: ubuntu-latest
    steps:
      - uses: matheusalbino/git-commit@v1.0.1
        with:
          user-name: workflows
          user-email: workflows@github-actions.com
          message: workflows npm publish
          github-token: ${{secrets.G_Token}}