name: NPM-Publish

on: 
  push:
    branches: [ master ]

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 10
      - uses: CultureHQ/actions-yarn@master
        with:
          args: install
      - run: npm config set commit-hooks false
      - run: npm config set git-tag-version false
        env:
          production: false
  
  build:
    needs: install
    runs-on: ubuntu-latest
    steps:
      - run: ls
      - run: ls node_modules
      - uses: CultureHQ/actions-yarn@master
        with:
          args: build