name: Node.js Package

on:
  release:
    types: [created]

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 10
          registry-url: https://registry.npmjs.org/
      - uses: CultureHQ/actions-yarn@master
        with:
          args: install
      - run: npm build
      - run: npm config set commit-hooks false
      - run: npm config set git-tag-version false
      - run: npm version patch
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_Token}}
      - uses: matheusalbino/git-commit@v1.0.1
        with:
          user-name: workflows
          user-email: workflows@github-actions.com
          message: workflows npm publish
          github-token: ${{secrets.G_Token}}
